<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="91242" started-at="2022-10-31T21:08:21Z" finished-at="2022-10-31T21:09:52Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="91242" started-at="2022-10-31T21:08:21Z" finished-at="2022-10-31T21:09:52Z">
      <class name="homeWork.checkAssertions">
        <test-method status="FAIL" signature="checkPageSource()[pri:0, instance:homeWork.checkAssertions@708f5957]" name="checkPageSource" duration-ms="23146" started-at="2022-11-01T02:38:21Z" finished-at="2022-11-01T02:38:44Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at homeWork.checkAssertions.checkPageSource(checkAssertions.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkPageSource -->
        <test-method status="PASS" signature="checkURL()[pri:0, instance:homeWork.checkAssertions@708f5957]" name="checkURL" duration-ms="41830" started-at="2022-11-01T02:38:59Z" finished-at="2022-11-01T02:39:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkURL -->
        <test-method status="PASS" signature="navigateLoginPage()[pri:0, instance:homeWork.checkAssertions@708f5957]" name="navigateLoginPage" duration-ms="1454" started-at="2022-11-01T02:39:46Z" finished-at="2022-11-01T02:39:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- navigateLoginPage -->
      </class> <!-- homeWork.checkAssertions -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
